### ISSUE TITLE
Icon gone after logout/reboot

### ISSUE THREAD

**Issue by p-try** [atareao/wireguard-indicator#6]
I had no issues with this extension on Ubuntu 20.10. On 21.04 now, the extension still works as expected but only until after I log out or reboot. The icon in the tray is gone but the extension is still listed as installed (marked with "ERROR"). Is there any way I can help to debug this?
Ubuntu 21.04 still comes with GNOME 3.38, but they switched to Wayland. Maybe this is of some interest.

**Comment by fabianthdev** [comment]
When loading on Wayland on Ubuntu 21.04, the extension tries to get the default GTK theme, however, due to changes in GNOME mutter when using Xwayland, GTK may not be available for extensions at loading time. This behavior is also described in the following issue in the GNOME mutter repository: https://gitlab.gnome.org/GNOME/mutter/-/issues/960.

I've created a pull request (#9) that fixes this error.

**Comment by atareao** [comment]
Fixed. Thanks to @fabianthdev
